[package]
name = "blakish"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
blake3 = "1.2"

[dependencies.neon]
version = "0.9"
default-features = false
features = ["napi-6"]
